### ISSUE TITLE
Errors when using the driver in Segger Embedded Studio

### ISSUE THREAD

**Issue by nit1995** [modm-io/Invensense-eMD#2]
I have downloaded the motion_driver_6.12 for Nordic Thingy 52. And I am using Segger Embedded Studio to build and debug the code. But the IDE is unable to find the libraries like accel_auto_cal.c, compass_vec_cal.c etc. When I include the path for libmpllib.a it shows around 120 errors which include multiple definitions for a lot of terms. I am using this on an Ubuntu OS. Would it be possible to help?

**Comment by salkinium** [comment]
This library is a port for using the eMD with modm.io and doesn‘t support IDEs of any kind. You will need to contact the official Invensense support for help.
